# -*- coding: utf-8 -*-
"""Untitled8.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1wfj8d6elIXqeqZ03I9As9Qaf9bAZdoCB
"""

!pip install pandas faker pyspark

from pyspark.sql import SparkSession
from pyspark.sql.functions import col, upper, explode
from pyspark.sql.types import StructType, StructField, IntegerType, StringType, FloatType, DateType
from datetime import datetime

spark = SparkSession.builder \
    .appName("SalesTransactionsAnalysis") \
    .config("spark.hadoop.fs.defaultFS", "file:///") \
    .getOrCreate()

product_data = spark.read.csv('/content/product_data.csv', header=True, inferSchema=True)

product_data.show()

best_rating = product_data.filter(col('rating') > 4.2)

best_rating.show()

# Distinct Products

distinct_products = product_data.select('product_id').distinct()
# distinct_products.show()
distinct_products = distinct_products.count()



# Distinct products having rating more than 4.2
distinct_best_products = best_rating.select('product_id').distinct()
# distinct_products.show()
distinct_best_products = distinct_best_products.count()
print(f"Overall products {distinct_products} & best products {distinct_best_products}")

sales_data = [
    (1, 101, 495988, 29.99, datetime(2024, 9, 1)),
    (2, 102, 279531, 49.99, datetime(2024, 9, 2)),
    (3, 103, 860476, 19.99, datetime(2024, 9, 3)),
    (4, 101, 163170, 99.99, datetime(2024, 9, 4)),
    (5, 104, 87079, 39.99, datetime(2024, 9, 5)),
    (6, 105, 112205, 59.99, datetime(2024, 9, 6)),
    (7, 103, 29408, 29.99, datetime(2024, 9, 7))
]

sales_schema = StructType([
    StructField("transaction_id", IntegerType(), True),
    StructField("customer_id", IntegerType(), True),
    StructField("product_id", IntegerType(), True),
    StructField("amount", FloatType(), True),
    StructField("date", DateType(), True)
])

sales_data = spark.createDataFrame(sales_data, sales_schema)

sales_data.show()

df_joined = product_data.join(sales_data, on='product_id', how='inner')
df_joined.show()

